name: Remote Workflow Triggered

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run-python-from-origin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo destino
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Checkout repo origem
        uses: actions/checkout@v4
        with:
          repository: leonardosete/teste-ricardinho-origem
#          ref: main                    # <<<< Ajuste o branch aqui!
          path: repo-origem
          token: ${{ secrets.GH_PAT }}

      - name: Executar o script Python do repo origem
        run: |
          python ./repo-origem/hello_from_origin.py
